cmake_minimum_required(VERSION 3.22)
project(stage192_cpp)
link_directories(/opt/ros/jazzy/lib)
find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(kdl_parser REQUIRED)
find_package(moveit_core REQUIRED)
find_package(moveit_kinematics REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(srdfdom REQUIRED)
find_package(urdf REQUIRED)
add_executable(stage192_direct_orocos_kdl ${CMAKE_CURRENT_SOURCE_DIR}/../stage192_direct_orocos_kdl.cpp)
ament_target_dependencies(stage192_direct_orocos_kdl kdl_parser urdf)
target_link_libraries(stage192_direct_orocos_kdl orocos-kdl)
add_executable(stage192_moveit_kdl_minimal ${CMAKE_CURRENT_SOURCE_DIR}/../stage192_moveit_kdl_minimal.cpp)
ament_target_dependencies(stage192_moveit_kdl_minimal geometry_msgs moveit_core moveit_kinematics moveit_msgs pluginlib rclcpp srdfdom urdf)
install(TARGETS stage192_direct_orocos_kdl stage192_moveit_kdl_minimal DESTINATION lib/${PROJECT_NAME})
ament_package()
